baseurl = "https://jimmysong.io/"
DefaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "zh-cn"
title = "Jimmy Song"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
#googleAnalytics = "XXX"

[Params]
hello = "Hi,I'm Jimmy"
subtitle = "I can help you building Cloud Native confidence"
logo = "https://res.cloudinary.com/jimmysong/raw/upload/rootsongjc-hugo/avatar-icon.png"
favicon = "https://res.cloudinary.com/jimmysong/raw/upload/rootsongjc-hugo/favicon.ico"
dateFormat = "January 2, 2006"
commit = false
rss = true
#comments = true
#sharebutton = true
algolia = "d2134c5a8d250e6d3246594240c45201" # API key
#gcse = "012737790962522169780:fd1izxsfgrs" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
description = "jimmysong.io|宋净超的博客|Cloud Native|Big Data"
errorpage = "https://res.cloudinary.com/jimmysong/image/upload/images/404-not-found-cat.png"

[[Params.bigimg]]
src = "https://res.cloudinary.com/jimmysong/image/upload/banners/keuc-cncf.jpg"
desc = "KEUC - China Kubernetes End User Conference 2017"

[[Params.bigimg]]
src = "https://res.cloudinary.com/jimmysong/image/upload/banners/kubernetes-meetup-china-20170826.jpg"
desc = "Kubernetes Beijing fans meetup - Aug 28,2017"

[[Params.bigimg]]
src = "https://res.cloudinary.com/jimmysong/image/upload/banners/cloud-computing.jpg"
desc = "Democratizing the Cloud Computing for every one"

[[Params.bigimg]]
src = "https://res.cloudinary.com/jimmysong/image/upload/banners/great-wall-01.jpg"
desc = "Insight throught the Great Wall to the world"

[[Params.bigimg]]
src = "https://res.cloudinary.com/jimmysong/image/upload/banners/big-data-1.jpg"
desc = "Using Big Data to make business decision"

[Author]
  name = "Jimmy Song(宋净超)"
  website = "https://jimmysong.io"
  email = "jimmysong@jimmysong.io"
  facebook = "jimmysongio"
  googleplus = "+jimmysong" # or xxxxxxxxxxxxxxxxxxxxx
  github = "rootsongjc"
  twitter = "jimmysongio"
  linkedin = "jimmysongio"
  500px = "jimmysongio"
  medium = "jimmysongio"
  instagram = "jimmysongio"
  weibo = "jimmysongio"

[[menu.main]]
    identifier = "Categories"
    name = "Categories"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "kubernetes"
    url = "categories/kubernetes"
    weight = 1
    
[[menu.main]]
    parent = "Categories"
    name = "Cloud Native"
    url = "categories/cloud-native"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "Microservices"
    url = "categories/microservices"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "Devops"
    url = "categories/devops"
    weight = 4

[[menu.main]]
    parent = "Categories"
    name = "Github"
    url = "categories/github"
    weight = 5

[[menu.main]]
    parent = "Categories"
    name = "Serverless"
    url = "categories/serverless"
    weight = 6

[[menu.main]]
    parent = "Categories"
    name = "Service Mesh"
    url = "categories/service-mesh"
    weight = 7

[[menu.main]]
    parent = "Categories"
    name = "Tags"
    url = "tags"
    weight = 8

[[menu.main]]
    identifier = "Gitbooks"
    name = "Gitbooks"
    weight = 2

[[menu.main]]
    parent = "Gitbooks"
    name = "Kubernetes handbook"
    url = "kubernetes-handbook"
    weight = 1

[[menu.main]]
    parent = "Gitbooks"
    name = "Docker handbook"
    url = "docker-handbook"
    weight = 2

[[menu.main]]
    parent = "Gitbooks"
    name = "Hugo Handbook"
    url = "hugo-handbook"
    weight = 3

[[menu.main]]
    parent = "Gitbooks"
    name = "Istio service mesh"
    url = "http://istio.doczh.cn"
    weight = 4

[[menu.main]]
    parent = "Gitbooks"
    name = "Migrating to Cloud Native"
    url = "migrating-to-cloud-native-application-architectures"
    weight = 5

[[menu.main]]
    identifier = "Publications"
    name = "Publications"
    weight = 3

[[menu.main]]
    parent = "Publications"
    name = "Cloud Native Go"
    url = "cloud-native-go"
    weight = 1

[[menu.main]]
    parent = "Publications"
    name = "Cloud Native Python"
    url = "posts/cloud-native-python"
    weight = 2

[[menu.main]]
    parent = "Publications"
    name = "Cloud Native Java"
    url = "posts/cloud-native-java"
    weight = 3

[[menu.main]]
    identifier = "Projects"
    name = "Projects"
    weight = 4

[[menu.main]]
    parent = "Projects"
    name = "Spark on kubernetes"
    url = "spark-on-k8s"
    weight = 1

[[menu.main]]
    parent = "Projects"
    name = "Awesome Cloud Native"
    url = "awesome-cloud-native"
    weight = 2

[[menu.main]]
    parent = "Projects"
    name = "Cloudinary go"
    url = "posts/cloudinary-go"
    weight = 3

[[menu.main]]
    parent = "Projects"
    name = "Magpie"
    url = "posts/yarn-on-docker"
    weight = 5

[[menu.main]]
    parent = "Projects"
    name = "Cheatsheets"
    url = "cheatsheets"
    weight = 6

[[menu.main]]
    name = "About"
    url = "about"
    weight = 7
