---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: bigimg
  label: Bigimg
  type: field_group_list
  fields:
  - name: src
    label: Src
    type: text
    hidden: false
    default: ''
  - name: desc
    label: Desc
    type: text
    hidden: false
    default: ''
  hidden: false
  default:
  - src: https://res.cloudinary.com/jimmysong/image/upload/images/2018040501.jpg
    desc: Flowers|Hangzhou|Apr 5,2018
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
